[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.zip",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.curl",
  "php82Extensions.fileinfo",
  "php82Extensions.bcmath",
  "php82Extensions.redis"
]
